name: agrisentinel_demo
description: "AgriSentinels mobile app for on-device maize disease and pest early warning."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  geolocator: ^10.1.0
  image: ^4.1.7
  shared_preferences: ^2.3.2
  flutter_map: ^7.0.2
  flutter_map_heatmap: ^0.0.8
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
